main: me.wand555.OWA.Main.OWA
name: OWA
version: 1.15.2
description: Test.
api-version: 1.13
author: wand555
commands:
  setwarp:
    usage: /setwarp <name>
    description: Has to be near a campfire to set a warp.
    permission: owa.setwarp
    message: &cYou dont have permission to set a campfire!
  delwarp:
    usage: /delwarp <name>
    description: Deletes warp given from name.
    permission: owa.delwarp
    message: &cYou dont have permission to set a campfire!
  warp:
    usage: /warp <name>
    description: Warps to the given name if existent. 
    permission: owa.warp.use
    message: &cYou dont have permission to teleport to a campfire!
permissions:
  owa.setwarp:
    description: Allows the player to set a warp near a camp
    default: op
  owa.delwarp:
    description: Allows the player to delete a warp they previously set
    default: op
  owa.warp:
    description: Allows the player to teleport to a warp he has.
    default: op
  owa.spawn:
    description: Decides whether zombies can spawn near him from the plugin
    default: op